 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  vgattr:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        test:
          url: https://drive.google.com/u/0/uc?id=13tWvOrNOLHxl3Rm9cR3geAdHx2qR3-Tw
          storage: data/ARO/prerelease_bow/visual_genome_attribution.json
      images:
          storage: data/ARO/prerelease_bow/images
