 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  coco_caption_iccc:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: 
            - data/coco/annotations/coco_karpathy_train_w_parsing.json # parsing results base
            - data/coco/annotations/coco_karpathy_train_cnter.json # concept base
      images:
        storage: data/coco/images
